items:
  - key: voice_engine
    value: PlayHT2.0-turbo
  - key: voice_id
    value: s3://voice-cloning-zero-shot/d9ff78ba-d016-47f6-b0ef-dd630f59414e/female-cs/manifest.json
  - key: sample_rate
    value: 44100
  - key: quality
    value: faster
  - key: speed
    value: 1
